apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 2Gi