apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: networking
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30915

    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30916

    - name: web
      port: 3001
      targetPort: 3000
      nodePort: 31628