apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: synology-csi
  sources:
    - repoUrl: https://christian-schlichtherle.github.io/synology-csi-chart
      chart: synology-csi-chart
      targetRevision: 0.10.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
