apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd
  git.argocd.argoproj.io/repo: manifests

resources:
  - applications.yaml
  - adguard-home
  - argocd
  - sealed-secrets
  - synology-csi
  - monitoring
  - traefik
  - coredns
  - synology-nfs-storageclass
  - synology-iscsi-storageclass
  - synology-pvc
  - nfs-subdir-external-provisioner
  - rabbitmq