apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
  name: synology-iscsi
provisioner: csi.san.synology.com
parameters:
  dsm: 192.168.68.138
  location: /volume1/k8s-iscsi
  protocol: "iscsi"
  fsType: "btrfs"
reclaimPolicy: Retain
allowVolumeExpansion: true
