apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.7
    chart: grafana
    helm:
      values: |
        adminPassword: "admin"
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: boulder.local
              paths:
                - path: /
                  pathType: Prefix
                  port: 8082
          tls: []
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true