---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB/6qU6Tgy4//SwXyrKPPKJvMaBtQoNSkxf5f28w6PtM8mKB9jgfh2Tc8hKdnzwsg2Y6xl9BhdjKlLt9qTxwHQKfLjlkTu3D8RqVikluQXBaWkHzf+sewG74C9PLjQiokp0eYvznacRcBcOv3avLmWQ17cylm4HXUt8W5WakWgjpxb3cPhzjGdvHV+0NElwLoN3ZLhmlAwyD6GYroU8LzmGPD/RKuB0wcxOXI3SGDV0hJ8sQrBLrImp6bWZYAlKu243HDiCfxhCUTHYMNqfIbX4B0wY77M4InoggOr8NljK/FrWQNYzRarAUA9AflDGLfib5t7XJfY3t1LqX+AcDGjsIpYkz/1j79u8c4LMB9X/XxYDpIUiYpRFWVt4V6xNHE85ZarEYCC6q6UiBvVcVK8Mr6zuqxFjMKecoUp/LlOePhaHNUn0UzPxIPP5cdm+6b2XKZd0c71Y+1x0JHg4PcjFBYv2AMEf1u2Xp7sUIFcmFEd/laxtxE/nkS0wbZFC8F6ljlK0w19HXvBbWizgqKJl4EWEqokF01Fxj93tt0pN+6XdnkMXMjYtTJBtfjwEuMJuLG3Bc5qaKWFq8zrhOObEby3xCmCxgW7gEWr0C1N4K+LpCGNO3hDf+/Efgtpc7ugfNlu0qie1tzqdd3cBIF19QGk1ZUTHW76bII4TONE32nqQ8KdfRxqKN/heITFzv7VsNZTvqqmBuBVLlSTehoi8
    admin-user: AgBNGgCXesJHwBUyLBvEaBr1EahQjMwh5FUW3PmhlAps4cA3BaCqWRivSc171RlZSC4+pXyb1fHOm3PzvgNoQoY0jAp+b25rHOef+kfUetxPgHCZ50FqR4METo9AaA15eSU55iaFmFR9FGQXQ8zdtYRM2Iv9a1cIG0YaZMXARZXA7HOLbXcXnl1MCc4Jj+qYwv+zlIKTKVzjcbwta8G8F4LmBQnC5pZH3vuIQ2+ejKjcqHrJt2CaEfj0iazrsS6Dk2Za8T35OrBXHNNfCx+3IwH6gkgsR8byaZI6oqUoXZABYIREGHLmLaHVgCz80CB79SaBcU+7nD6SU1iRUMSwkwMrfyhvM1x8lQrS5MnHD53uLBSrTQXTZ1Xxf/Xw65N+LiDNwCrnQpUj4lrfjTIMGhRUYs4LWogwDf/elWIxTB+0WaNz9+8UnbkGVQeecEpsdKJhPDyI2rylKS6HusIsH8UOwl+wHJNL5UOGJZvP/Qmedvn8K7zE51IVe0W4wRRikD9JlOCUJxooWdxpMeE9TteFKKpmBuX+czYqH/H9B7ci3oD4l4c0wZYqh8G5bTa8f95VS+0Af4s/o0zIS0svkzSBMKUJXUis+Rcif9nDBDLFTjqFK67lu1OViC2jDO3McL+6PTZsZrTpTDoQlg/MUJjjL2tJz3rXaPHnTsDDsLK9+Qo7+F0RkzF+7QrrIbX0A8Aid3jBwg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        infrastructure.io/component: observability
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
