apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.7
    chart: grafana
    helm:
      values: |
        adminPassword: "admin"
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true