apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.55.0
    chart: loki
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              ruler: ruler
        singleBinary:
          replicas: 1
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
