apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.21.0
    chart: prometheus
    helm:
      values: |
        server:
          service:
            type: ClusterIP
        extraScrapeConfigs: |
          - job_name: 'argocd'
            static_configs:
              - targets:
                - argo-argocd-application-controller-metrics.argocd.svc:8082/metrics
                - argo-argocd-server-metrics.argocd.svc:8083/metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
