apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.7.12
    helm:
      releaseName: argo
      values: |
        configs:
          params:
            server.insecure: "true"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
