apiVersion: v1
kind: Secret
metadata:
  name: bitnami-helm-repo
  namespace: argocd
  annotations:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.bitnami.com/bitnami
  type: helm
  name: bitnami
  username: ""   # required even if public
  password: ""   # required even if public