apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-server
  namespace: argocd
spec:
  entryPoints:
    - argocd
  routes:
    - kind: Rule
      match: Host(`boulder1.local`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`boulder1.local`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
