apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- argocd.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    namespace: argocd
    behavior: merge
    literals:
      - "server.insecure=true"
