apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  infrastructure.io/component: messaging

resources:
  - namespace.yaml
  - rabbitmq-operator.yaml
  - rabbitmq.yaml
  - rabbitmq-sealed-secret.yaml
  - rabbitmq-configmap.yaml
