apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  name: synology-nfs
provisioner: csi.san.synology.com
parameters:
  dsm: 192.168.68.138
  location: /volume1/kubernetes
  mountPermissions: "0755"
  protocol: "nfs"
mountOptions:
  - vers=4.1
reclaimPolicy: Retain
allowVolumeExpansion: true
