---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: adguard-secret
  namespace: networking
spec:
  encryptedData:
    users.yaml: AgBLTVeNyk67S1CnIoJa4Y3rA8pqSRq0IdZimFQ2sijiE8x9u06+wEM+2XCDzPE+Kcmj2mFy0UqbHxUnPaBnbnlV6Re6H0kaV9QoPy3tSU5yHymYYSQf4V75eS2QcvaJLDf1QAtGi58ZzS8OLkDIO13hqFelztP6A2aTdiTp8yuKB/X4DxvroNexNRVByQNyd54ZVbW6VzSLhJ11j0Nves8pc/9VG6bKWghuxP4vBXFkkSMcfCHKmqmjF/m2mmW2/W7rDmhF34RUI1gC9br8+Lzma8m3Tk8ILWEkADgieOu3L29LQAdBS+2VYHkcSmbvhE++MK07I8DO12pd22CRo29GHsx07uiF13wVzCQVmEzYKo0xFXPIqqhg+BY4kBrBs7wQgwbMMOZCXM62d1DJec9AIsE3OuQldcBme7JwG6/Np6LHLVN+UxFwOL5XDeDZAKup2ubDgI0LqdCg82ACp02cItQf1YPXibabdRVzppMtT4lzpn7c0XtPn8vbiYAqxS6DXHLgz8jdBVyDrpgf7HNkSpaqHwvKgn4yQutyGAQCVd6afr//wofsgSoFjbIZ4US9zXm2+sF3KRQbUiJUo/ah/Jhkh9eRAqHL1XltjjioNDfQih3wuiCP4trsJQSdIef1Hs+gczHXW0oPEfJXNVXp1gpf7j+j019cTP1aPAvPwTXtTogpO9zDrBpQmoOoGNUULGeKYrY1zlJs4znDpCm6Cmm1c503p+SOHWAg7vC4oytDiPk/78eQ40OQapmClXP8DiybEK3X5x0vqr10v6Tk1cbuBwRujz81urPkmDTAee7Rrsw8JRNOotQGcK3zBtM3/S3S
  template:
    metadata:
      creationTimestamp: null
      name: adguard-secret
      namespace: networking
    type: Opaque
